### ISSUE TITLE
Why restricting to QC

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondolib#4]
We want to work on a set of user friendly abstractions for our ontologies in python:

```
mondo = Mondo()
print(mondo.get_features_of('MONDO:123'))
> HP:123
mondo.get_causative_genes('MONDO:123')

etc, essentially wrapping OAK and adding some custom stuff on top.  Should this be a different toolkit?
```

**Comment by joeflack4** [comment]
I was considering starting up a `mondo-utils` repo if one didn't already exist. But I see this now. @matentzn If I start that up, should I just make PRs to this repo or start a new one?

If starting a new one, maybe this repo should be renamed to `mondo-qc-lib`.

**Comment by matentzn** [comment]
No lets all work on this one here - coordinate closely with @hrshdhgd who is also implementing something soon!

**Comment by joeflack4** [comment]
@matentzn If that's the case, all that I think might need to be done here is to remove the word "QC" from the `README.md`. Unless we also need to convince Chris/Harshad, but I feel they'll agree.

**Comment by matentzn** [comment]
Yea let's do that.

**Comment by joeflack4** [comment]
Sounds good. Opened #6 and connected this issue to it.
